# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Powershell project to Azure Function App - cipphzozq

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # path to your app

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      # ðŸ”‘ Login to Azure first
      - name: Azure login (publish profile)
        uses: azure/login@v2
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_API }}

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'cipphzozq'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_API }}

  configure:
    needs: deploy
    runs-on: ubuntu-latest  # Linux runner for azure/cli
    steps:
      - name: Azure login (publish profile)
        uses: azure/login@v2
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_API }}

      - name: Set CIPP SuperAdmin + enable roles (Function App)
        uses: azure/
