# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Powershell project to Azure Function App - cipphzozq

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'cipphzozq'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
              # Add CIPP SuperAdmin + enable roles
    - name: Set CIPP SuperAdmin + enable roles
      uses: azure/cli@v2
      with:
        inlineScript: |
          az webapp config appsettings set \
            --name cipphzozq \
            --resource-group cipp \
            --settings SUPERADMINS=ash.crompton@netserve.support ENABLE_ROLES=true
          az webapp restart \
            --name cipphzozq \
            --resource-group cipp
            
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AC7DBB52700345BFB01628026843B37E }}
